name: Build and Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master' 
      k8s_context:
        description: 'Kubernetes context to use (e.g., vps-kube, local-kube)'
        required: true
        type: choice 
        options:
          - vps-kube
          - local-kube
        default: 'vps-cluster'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from selected branch
        uses: actions/checkout@v4  
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0  

      - name: Get commit SHA from branch
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3  
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:${{ env.COMMIT_SHA }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:${{ env.COMMIT_SHA }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4  
        with:
          version: 'latest'

      - name: Configure kubeconfig and switch context
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
        
          echo "${KUBECONFIG_DATA}" > kubeconfig 
          export KUBECONFIG=$(pwd)/kubeconfig
          
         
          kubectl config use-context ${{ github.event.inputs.k8s_context }}
          
         
          kubectl config current-context

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ runner.temp }}/kubeconfig 
        run: |
          
          export KUBECONFIG=${{ env.KUBECONFIG }}  
          

          kubectl set image deployment/myapp myapp=ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:${{ env.COMMIT_SHA }} -n default

          kubectl rollout status deployment/myapp -n default --timeout=300s

