name: Build and Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'
      k8s_context:
        description: 'Kubernetes context to use'
        required: true
        default: 'vps-cluster'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/myapp:${{ github.event.inputs.branch }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBE_CONFIG=$PWD/kubeconfig

      - name: Deploy to Kubernetes
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/myapp:${{ github.event.inputs.branch }}
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          kubectl --context=${{ github.event.inputs.k8s_context }} set image deployment/myapp myapp=$IMAGE_NAME
          kubectl --context=${{ github.event.inputs.k8s_context }} rollout status deployment/myapp

