name: Manual Build and Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Выберите ветку для сборки и деплоя'
        required: true
        type: choice
        options:
          - master
          - dev
        default: 'master'
      k8s_server:
        description: 'Выберите сервер для деплоя'
        required: true
        type: choice
        options:
          - vps-kube
          - local-kube
        default: 'vps-kube'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.event.inputs.branch }}
          docker build -t ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:$IMAGE_TAG .
          docker push ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:$IMAGE_TAG

      - name: Configure kubeconfig for selected server
        run: |
          if [ "${{ github.event.inputs.k8s_server }}" == "vps-kube" ]; then
            echo "${{ secrets.KUBE_CONFIG_VPS }}" > kubeconfig
          elif [ "${{ github.event.inputs.k8s_server }}" == "local-kube" ]; then
            echo "${{ secrets.KUBE_CONFIG_LOCAL }}" > kubeconfig
          else
            echo "Неизвестный сервер: ${{ github.event.inputs.k8s_server }}"
            exit 1
          fi
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config current-context || (echo "Ошибка: current-context не установлен — проверьте секрет"; exit 1)

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          IMAGE_TAG=${{ github.event.inputs.branch }}
          DEPLOYMENT="myapp"
          kubectl set image deployment/$DEPLOYMENT myapp=ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:$IMAGE_TAG -n default
          kubectl rollout status deployment/$DEPLOYMENT -n default --timeout=300s

