name: Build and Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'
      k8s_context:
        description: 'Kubernetes context/server to use'
        required: true
        type: choice
        options:
          - vps-kube
          - local-kube
        default: 'vps-kube'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:${{ github.sha }}

      - name: Configure kubeconfig
        run: |
          if [ "${{ github.event.inputs.k8s_context }}" == "vps-kube" ]; then
            echo "${{ secrets.KUBE_CONFIG_VPS }}" > kubeconfig
          elif [ "${{ github.event.inputs.k8s_context }}" == "local-kube" ]; then
            echo "${{ secrets.KUBE_CONFIG_LOCAL }}" > kubeconfig
          else
            echo "Unknown k8s_context: ${{ github.event.inputs.k8s_context }}"
            exit 1
          fi
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/myapp myapp=ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:${{ github.sha }} -n default
          kubectl rollout status deployment/myapp -n default --timeout=300s

